version: '3.3'
services:
  db:
    image: 'mysql:8'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: imdb_MovieLens
    volumes:
      - './src/main/resources/sql/keretrendszer_beadando.sql:/docker-entrypoint-initdb.d/keretrendszer_beadando.sql'
    ports:
      - '127.0.0.1:3306:3306'
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: imdb_MovieLens
      DB_USER: root
      DB_PASSWORD: password
    depends_on:
      - db
